---
# Create  server policies specific to Converged Infrastrucure stack
- name: "Create IMM Server Policies"
  vars:
    api_info: &api_info_org_moid
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info_org_moid
    resource_path: /organization/Organizations
    query_params:
      $filter: "Name eq '{{ org_name }}'"
  register: intersight_org
  delegate_to: localhost
  tags: always
  run_once: true

# Collect information on existence of Boot Order Policy, LAN Connectivity Policy, and
# IMC Management IP Pool
- include_tasks: gather_policy_info.yml

# Collect information about various pools
- include_tasks: gather_pool_info.yml

# Create Boot Policy
# - include_tasks: create_boot_order_policies.yml

# Create Cohesity Boot Order Policy
- include_tasks: create_boot_order_policies.yml

# Create Cohesity Power Policy
- include_tasks: create_power_policy.yml

# Create BIOS Policy
# - include_tasks: create_bios_policies.yml

- include_tasks: create_bios_policies.yml

# Create IMC Policy
# - include_tasks: create_imc_policy.yml

- include_tasks: create_imc_policy.yml

# Create Virtual Media Policy
# - include_tasks: create_vmedia_policy.yml

- include_tasks: create_vmedia_policy.yml

# Create IPMI over LAN Policy to enable IPMI over LAN
- include_tasks: create_ipmi_policy.yml

# Create SerialOver LAN Policy
- include_tasks: create_sol_policy.yml

# Create Local User Policy to allow KVM Access
- include_tasks: create_local_user_policy.yml
  when:  (local_user_policy.api_response.Moid is not defined)

# Create KVM Policy
- include_tasks: create_kvm_policy.yml

# Create Ethernet QoS Policy
- include_tasks: create_ethernet_qos_policy.yml

# Create Ethernet Network Control Policy
- include_tasks: create_ethernet_network_control_policy.yml

# Create VMware and High Traffic Ethernet Adapter Policy
- include_tasks: create_ethernet_adapter_policies.yml

# Create Ethernet Network Group Policy - VLAN details for vNICs assigned for Management and Data
- include_tasks: create_ethernet_network_group_policy.yml

# Configure  LAN Connectivity Policy
- include_tasks: create_lan_connectivity_policy.yml
  when:  (lan_connectivity_policy_details.api_response.Moid is not defined)
